name: Build & deploy django project

on:
  push:
    branches:
      - main

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
      
    steps:
      - uses: actions/checkout@v2

      - name: Setup python environment
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          
      - name: Run migrations
        run: |
          python manage.py makemigrations
          python manage.py migrate

  heroku_git_deploy_job:
      runs-on: ubuntu-latest
      needs: build
      name: Deploy
      steps:
        - name: Checkout
          uses: actions/checkout@v2
        - name: Deploy django to heroku
          uses: PedroAntonioFS/Exemplo-github-actions@v1
          with: 
            heroku_app_name : ${{ secrets.HEROKU_APP_NAME }}
            heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
            heroku_email_address: 'p.antonio.f.s@gmail.com'
            use_git: true
